"""Known spellings for the most frequent Darija words.

Character-level transliteration cannot recover short vowels, because arabizi
does not write them. ``salam`` maps letter by letter to ``سالام`` when the
correct spelling is ``سلام``: the ``a`` is a fatha, not an alef, and nothing in
the input says which.

No rule fixes this. What does fix it, for the words that matter most, is a
lookup table: a few hundred function words and greetings account for a large
share of any Darija text, and their spellings are settled. The transliterator
consults this first and falls back to the character mapping for everything
else.

Keys are lowercase and free of punctuation. Several spellings of the same word
map to the same output, because arabizi spelling is not standardised.
"""

from __future__ import annotations

WORD_SPELLINGS: dict[str, str] = {
    # greetings and set phrases
    "salam": "سلام",
    "salamo": "سلام",
    "labas": "لاباس",
    "labass": "لاباس",
    "bikhir": "بخير",
    "bkhir": "بخير",
    "hamdullah": "الحمد لله",
    "lhamdullah": "الحمد لله",
    "inchallah": "إن شاء الله",
    "nchallah": "إن شاء الله",
    "barakallah": "بارك الله",
    "bsse7a": "بصحة",
    "bssaha": "بصحة",
    "yallah": "يالله",
    "wakha": "واخا",
    "3afak": "عفاك",
    "3afakoum": "عفاكم",
    "smh": "سمح",
    "smhli": "سمح ليا",
    "chokran": "شكرا",
    "choukran": "شكرا",
    # interrogatives
    "wach": "واش",
    "wash": "واش",
    "chno": "شنو",
    "chnou": "شنو",
    "shnu": "شنو",
    "achno": "أشنو",
    "chkoun": "شكون",
    "shkoun": "شكون",
    "kifach": "كيفاش",
    "kifash": "كيفاش",
    "3lach": "علاش",
    "3lash": "علاش",
    "fin": "فين",
    "fayn": "فين",
    "mnin": "منين",
    "imta": "إمتى",
    "chhal": "شحال",
    "ch7al": "شحال",
    "wo9tach": "وقتاش",
    # pronouns
    "ana": "أنا",
    "nta": "نتا",
    "nti": "نتي",
    "howa": "هوا",
    "hiya": "هيا",
    "7na": "حنا",
    "hna": "حنا",
    "ntoma": "نتوما",
    "homa": "هوما",
    # determiners and particles
    "dyal": "ديال",
    "dial": "ديال",
    "dyali": "ديالي",
    "dyalk": "ديالك",
    "dyalo": "ديالو",
    "dyalha": "ديالها",
    "dyalna": "ديالنا",
    "had": "هاد",
    "hadi": "هادي",
    "hada": "هادا",
    "hadchi": "هادشي",
    "dakchi": "داكشي",
    "dak": "داك",
    "chi": "شي",
    "shi": "شي",
    "li": "لي",
    "lli": "اللي",
    "elli": "اللي",
    "kol": "كل",
    "kul": "كل",
    "ga3": "گاع",
    "wa7d": "واحد",
    "wahd": "واحد",
    "we7d": "واحد",
    # quantity and manner
    "bzaf": "بزاف",
    "bzzaf": "بزاف",
    "chwiya": "شوية",
    "shwiya": "شوية",
    "mzyan": "مزيان",
    "mzyana": "مزيانة",
    "safi": "صافي",
    "b7al": "بحال",
    "bhal": "بحال",
    "kima": "كيما",
    "ghir": "غير",
    "walo": "والو",
    # verbs
    "kayn": "كاين",
    "kayna": "كاينة",
    "kaynin": "كاينين",
    "makaynch": "ما كاينش",
    "bghit": "بغيت",
    "bghiti": "بغيتي",
    "bgha": "بغا",
    "mabghitch": "ما بغيتش",
    "khass": "خاص",
    "khassni": "خاصني",
    "khassk": "خاصك",
    "3ndi": "عندي",
    "3andi": "عندي",
    "3ndek": "عندك",
    "3ndo": "عندو",
    "dir": "دير",
    "diri": "ديري",
    "ndir": "ندير",
    "gal": "گال",
    "goul": "گول",
    "chouf": "شوف",
    "shouf": "شوف",
    "3raft": "عرفت",
    "3arf": "عارف",
    "ma9darch": "ما قدرتش",
    "ma9dartch": "ما قدرتش",
    "nmchi": "نمشي",
    "mchit": "مشيت",
    "ja": "جا",
    "jit": "جيت",
    # time
    "daba": "دابا",
    "ghadi": "غادي",
    "ghadya": "غادية",
    "gha": "غا",
    "lyoum": "اليوم",
    "lbare7": "البارح",
    "ghedda": "غدا",
    # negation and connectors
    "machi": "ماشي",
    "mashi": "ماشي",
    "walakin": "ولكين",
    "wlakin": "ولكين",
    "wla": "ولا",
    "awla": "أولا",
    "3la": "على",
    "3lik": "عليك",
    "3lia": "عليا",
    "men": "من",
    "mn": "من",
    "m3a": "معا",
    "m3ak": "معاك",
    "ila": "إلا",
    "bach": "باش",
    "bash": "باش",
    "7it": "حيت",
    "hit": "حيت",
    "7ta": "حتى",
    "hta": "حتى",
    # common nouns
    "dar": "دار",
    "khouya": "خويا",
    "khti": "ختي",
    "weld": "ولد",
    "bnt": "بنت",
    "flous": "فلوس",
    "khdma": "خدمة",
    "3ayn": "عين",
    "rass": "راس",
    "7aja": "حاجة",
    "haja": "حاجة",
    "nass": "ناس",
    "blad": "بلاد",
    "triq": "طريق",
    "tri9": "طريق",
}
